openapi: 3.0.0
info:
  description: 'The purpose of this application is to provide documentation of the APIs in services-amagi-tv


    # Authentication


    <!-- ReDoc-Inject: <security-definitions> -->'
  title: services-amagi-tv Add User Status API
  contact:
    email: suvrojyoti@amagi.com
  version: null
servers:
- url: https://r5i37dwfp8.execute-api.us-east-1.amazonaws.com/dev/
  description: Development Server
- url: https://services.amagi.tv
  description: Production Server
tags:
- name: Status
paths:
  /status/{id}:
    get:
      security:
      - TokenAuth: []
      summary: Gets status of a submitted job, requires operator access
      parameters:
      - $ref: '#/components/parameters/jobID'
      responses:
        '200':
          description: Job status
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                properties:
                  status:
                    $ref: '#/components/schemas/JobStatus'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '500':
          description: Internal Server Error
      tags:
      - Status
components:
  schemas:
    errorMessage:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          required:
          - status
          - message
          - code
          properties:
            status:
              type: integer
              description: HTTP Status Code
            message:
              type: string
              description: Error description
            code:
              type: string
              description: Pre defined Error code
    JobStatus:
      description: Job status
      title: status represents the Job status
      type: string
      enum:
      - REJECTED
      - QUEUED
      - RUNNING
      - FAILED
      - SUCCEEDED
      - CANCELLING
      - CANCELLED
  parameters:
    jobID:
      name: id
      in: path
      description: Job ID
      required: true
      schema:
        type: string
  responses:
    notFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    UnauthorizedError:
      description: Token key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
  securitySchemes:
    access-key:
      type: apiKey
      in: header
      name: access_key
    secret-key:
      type: apiKey
      in: header
      name: secret_key
