openapi: 3.0.0
info:
  description: 'The purpose of this application is to provide documentation of the APIs in services-amagi-tv


    # Authentication


    <!-- ReDoc-Inject: <security-definitions> -->'
  title: services-amagi-tv Add User Logs API
  contact:
    email: suvrojyoti@amagi.com
  version: "1.0"
servers:
- url: https://r5i37dwfp8.execute-api.us-east-1.amazonaws.com/dev/
  description: Development Server
- url: https://services.amagi.tv
  description: Production Server
tags:
- name: Logs
paths:
  /logs/{id}:
    get:
      security:
      - TokenAuth: []
      summary: Returns logs of a job, requires operator access
      parameters:
      - $ref: '#/components/parameters/jobID'
      responses:
        '200':
          description: Returns logs of a job
          content:
            text/plain:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '500':
          description: Internal Server Error
      tags:
      - Logs
components:
  schemas:
    errorMessage:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          required:
          - status
          - message
          - code
          properties:
            status:
              type: integer
              description: HTTP Status Code
            message:
              type: string
              description: Error description
            code:
              type: string
              description: Pre defined Error code
  parameters:
    jobID:
      name: id
      in: path
      description: Job ID
      required: true
      schema:
        type: string
  responses:
    notFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    badRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    UnauthorizedError:
      description: Token key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
  securitySchemes:
    access-key:
      type: apiKey
      in: header
      name: access_key
    secret-key:
      type: apiKey
      in: header
      name: secret_key
