openapi: 3.2.0
info:
  description: 'The purpose of this application is to provide documentation of the APIs in mapsor


    # Authentication


    -->'
  title: Mapsor Cancel API
  contact:
    email: arpitm@amagi.com
  version: 0.2.0
servers:
- url: https://pbohw6r8e1.execute-api.us-east-1.amazonaws.com/dev/?token=Vqv80iwJyHVPreFu47dNYg
  description: Development Server
- url: https://api.mapsor.amagi.tv
  description: Production Server
tags:
- name: Cancel
paths:
  /cancel/{id}:
    get:
      security:
      - TokenAuth: []
      summary: Cancel a job, requires operator access
      parameters:
      - $ref: '#/components/parameters/jobID'
      responses:
        '200':
          description: Cancel a job
          content:
            application/json:
              schema:
                type: object
                required:
                - response
                properties:
                  response:
                    type: string
                    description: Response
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '500':
          description: Internal Server Error
      tags:
      - Cancel
      operationId: getCancelById
      x-operation-id-source: derived
components:
  responses:
    UnauthorizedError:
      description: Token key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    notFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    badRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
  parameters:
    jobID:
      name: id
      in: path
      description: Job ID
      required: true
      schema:
        type: string
  schemas:
    errorMessage:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          required:
          - status
          - message
          - code
          properties:
            status:
              type: integer
              description: HTTP Status Code
            message:
              type: string
              description: Error description
            code:
              type: string
              description: Pre defined Error code
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: query
      name: token
