openapi: 3.0.0
info:
  description: 'The purpose of this application is to provide documentation of the APIs in services-amagi-tv


    # Authentication


    <!-- ReDoc-Inject: <security-definitions> -->'
  title: services-amagi-tv Add User List Keys API
  contact:
    email: suvrojyoti@amagi.com
  version: "1.0"
servers:
- url: https://r5i37dwfp8.execute-api.us-east-1.amazonaws.com/dev/
  description: Development Server
- url: https://services.amagi.tv
  description: Production Server
tags:
- name: List Keys
paths:
  /list-keys:
    get:
      security:
      - access-key: []
        secret-key: []
      summary: Lists all keys having common prefix-key, requires user access_key and secret_key
      operationId: listKeys
      parameters:
      - name: key_prefix
        in: query
        schema:
          type: string
        required: true
        description: Key Prefix
      responses:
        '200':
          description: Display all keys having common prefix as 'key_prefix'
          content:
            application/json:
              schema:
                type: object
                required:
                - data
                properties:
                  data:
                    type: string
                    description: array of keys
                  error:
                    type: string
                    description: User Error
                example:
                  data:
                  - ETag: b488c97f5580c8287393cc4385156776
                    Key: CUSTOMER-NAME/FEED1/config1.json
                    LastModified: Sun, 25 Jul 2021 15:08:46 GMT
                  - ETag: 81e9e47ca1dc97db927e191eddd270c9
                    Key: CUSTOMER-NAME/FEED2/config2.json
                    LastModified: Mon, 26 Jul 2021 09:22:55 GMT
                  error: null
        '401':
          $ref: '#/components/responses/ServiceError'
        '500':
          description: Internal Server Error
      tags:
      - List Keys
components:
  schemas:
    errorMessage:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          required:
          - error
          properties:
            error:
              type: string
              description: Error description
  responses:
    ServiceError:
      description: Service error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
  securitySchemes:
    access-key:
      type: apiKey
      in: header
      name: access_key
    secret-key:
      type: apiKey
      in: header
      name: secret_key
