openapi: 3.0.0
info:
  description: 'The purpose of this application is to provide documentation of the APIs in services-amagi-tv


    # Authentication


    <!-- ReDoc-Inject: <security-definitions> -->'
  title: services-amagi-tv Add User Regenerate Token API
  contact:
    email: suvrojyoti@amagi.com
  version: "1.0"
servers:
- url: https://r5i37dwfp8.execute-api.us-east-1.amazonaws.com/dev/
  description: Development Server
- url: https://services.amagi.tv
  description: Production Server
tags:
- name: Regenerate Token
paths:
  /regenerate-token:
    post:
      security:
      - TokenAuth: []
      summary: Regenerates auth token for an existing user, requires admin's auth token
      operationId: regenerateTokenForExistingUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - user
              properties:
                user:
                  type: string
                  description: Username
              example:
                user: cloudport
      responses:
        '201':
          description: Successfully Regenerated token for user
          content:
            application/json:
              schema:
                type: object
                required:
                - token
                - message
                properties:
                  token:
                    type: string
                    description: Token
                  message:
                    type: string
                    description: User message
                example:
                  token: kjrtklnhgcyk
                  message: Please keep the token safely. It cannot be retrieved again
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '409':
          $ref: '#/components/responses/conflictResourceError'
        '500':
          description: Internal Server Error
      tags:
      - Regenerate Token
components:
  schemas:
    errorMessage:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          required:
          - status
          - message
          - code
          properties:
            status:
              type: integer
              description: HTTP Status Code
            message:
              type: string
              description: Error description
            code:
              type: string
              description: Pre defined Error code
  responses:
    badRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    conflictResourceError:
      description: Image Already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    forbiddenError:
      description: Forbidden to access the resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
    UnauthorizedError:
      description: Token key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorMessage'
  securitySchemes:
    access-key:
      type: apiKey
      in: header
      name: access_key
    secret-key:
      type: apiKey
      in: header
      name: secret_key
